#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTBOT_DIR="submodules/dotbot"
DOTBOT_BIN="bin/dotbot"

CONFIG="install.conf.yaml"

cd "$BASEDIR"
git -C "$DOTBOT_DIR" submodule sync --quiet --recursive
echo "Downloading all git submodules"
git submodule update --init --recursive

"$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
    -d "$BASEDIR" \
    --plugin-dir submodules/dotbot-brew \
    -c "$CONFIG" "$@"
