#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$BASE_DIR/internal/scripts"

set +u; source "$BASE_DIR/shell/profile"; set -u
source "$SCRIPTS_DIR/helpers.sh"

# On macOS and Linux I've had issues where apps that are launched from some form of dock or launcher
# (e.g. spotlight) use the system's default login shell (zsh, bash) instead of fish even if fish is
# configured as the login shell. When the environment is set up in config.fish, this can cause the
# app to have the wrong environment. To fix this, I store my environment variables in a separate
# profile file and load them from there. This function configures other shells like bash and zsh to
# also load the profile just in case the problem above happens.
setup_profiles() {
    local shell_configs=("$HOME/.bash_profile" "$HOME/.zprofile" "$HOME/.profile")

    local old_start="# Added by dotfiles installer"
    local old_command="source '$BASE_DIR/shell/profile'"
    local old_pattern="$old_start\n$old_command"
    for config in "${shell_configs[@]}"; do
        if [[ ! -f "$config" ]]; then
            continue
        fi

        if ! grep --quiet --null-data "$old_pattern" "$config"; then
            continue
        fi

        # The initial copy here is just so that our new file has the same permissions as the
        # existing file. The chmod and chown command on macOS don't support --reference.
        log "Removing old shell profile command from '$config'"
        cp -p "$config" "$config.tmp"
        sed -e "\|$old_start|d" -e "\|$old_command|d" "$config" > "$config.tmp"
        mv "$config.tmp" "$config"
    done

    local block_start="# Start of dotfiles section"
    local block_cmd="if [ -f '$BASE_DIR/shell/profile' ]; then source '$BASE_DIR/shell/profile'; fi"
    local block_end="# End of dotfiles section"
    for config in "${shell_configs[@]}"; do
        if [[ -f "$config" ]] && grep -q "$block_start" "$config"; then
            log "Source command has already been added to '$config'"
            continue
        fi

        log "Adding source command to '$config'"
        {
            echo
            echo "$block_start"
            echo "$block_cmd"
            echo "$block_end"
        } >> "$config"
    done
}

main() {
    if ! on_macos && ! on_linux; then
        echo "Unsupported operating system"
        return 1
    fi

    log "Installing packages"
    "$SCRIPTS_DIR/install-packages.sh"

    log "Setting up the shell"
    "$SCRIPTS_DIR/configure-shell.sh"

    log "Setting up Git"
    "$SCRIPTS_DIR/configure-git.sh"

    cd "$BASE_DIR"
    log "Downloading all git submodules"
    git submodule update --init --recursive

    log "Setting up symbolic links"
    "$SCRIPTS_DIR/manage-symlinks.sh"

    # This might be the first time we installed a theme for bat, in which case we need to rebuild
    # it's cache for the theme to become usable. This doesn't take long, so I'm doing it on every
    # run for now.
    log "Rebuilding bat's cache"
    bat cache --build

    log "Configuring other shells to load the custom profile"
    setup_profiles

    log
    log "You will likely need to set your terminal to load fish as its default command, or install"
    log "a terminal with a config already present in these configs. If you want to quickly get into"
    log "fish to test, you can run 'exec bash -l' to pickup the new environment and then 'exec fish'"
    log
    log "Installation complete."
}

main "$@"
