tap "homebrew/services"

brew "bat"
brew "curl"
brew "exa"
brew "fd"
brew "fish"
brew "gh"
brew "git"
brew "go"
brew "gum"
brew "jq"
brew "less"
brew "neovim"
brew "node"
brew "python@3.10"
brew "ripgrep"
brew "shellcheck"
brew "starship"
brew "virtualenv"
brew "wget"
brew "xsel" # Linux clipboard handler that is required for neovim to use the clipboard
