#!/usr/bin/env bash
#
# Run all installers

set -e 
cd "$(dirname $0)"/..
# Find all installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done