#!/usr/bin/env bash
# ----------------------------------------------------------------------------------------------------------------------
# install
# Install is used to run all of the installers within the dotfiles repository. Any file named install.sh will be found
# and run by this script.
# ----------------------------------------------------------------------------------------------------------------------

set -e 
cd "$(dirname "$0")"/..
source scripts/common/logging.sh

find . -name install.sh | 
    while read -r installer ; do 
        echo
        log_warn "Found installer: $installer"
        log_question "Press RETURN to run or any other key to skip..."
        read -rsN1 char </dev/tty
        if ! [[ "$char" == $'\n' || "$char" == $'\r' ]]; then
            log_success "Skipped $installer"
            continue
        fi
        
        log_info "Running installer... ($installer)"
        # The sed pipe adds tabs before output to separate it visually
        sh -c "${installer}" 2>&1 | sed 's/^/    /'
        log_success "Finished running installer."
    done