# https://espanso.org/docs/matches/basics/
matches:
  # awk sorts the output of `docker ps` by container name (first column) but skips the output header
  - trigger: dps
    replace: docker ps -a --format 'table {{.Names}}\t{{.Status}}' | awk 'NR<2{print$0;next}{print $0 | "sort"}'
  - trigger: dpps
    replace: docker ps -a --format 'table {{.Names}}\t{{.Ports}}' | awk 'NR<2{print$0;next}{print $0 | "sort"}'
